- name: agee
  hosts: all
  tasks:
    - name: install httpd
      apt:
        name: httpd
        state: installed
        update_cache: true 
       notify:
        - Start Httpd
         
   handlers:
    - name: Start Httpd
      service:
       name: httpd
       state: started
