- name: handlerstest
  hosts: test
  tasks:
     - name: copy file
       copy: src=/etc/passwd dest=/tmp/a.txt
       notify: testhandlers
  handlers:
     - name: testhandlers
       shell: echo "it's OK !" >> /tmp/a.txt
